//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MySaver.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_MYSAVER_DIALOG              102
#define IDC_POINTER                     104
#define IDD_OPTIONAL_SETTINGS           105
#define IDD_CONFIRM_PASSWORD            106
#define IDD_ENTER_PASSWORD              107
#define IDR_MAINFRAME                   128
#define IDD_PP0                         129
#define IDD_PP1                         130
#define IDD_PP2                         132
#define IDB_WIZARD_HEADER               135
#define IDB_WIZARD_WATERMARK            136
#define IDD_DIALOG1                     137
#define IDD_WELCOME                     138
#define IDD_DIALOG2                     139
#define IDS_PP3_DESC                    139
#define IDD_REGISTER_PRODUCT            140
#define IDD_ACTIVATE                    141
#define IDI_ICON1                       142
#define IDD_PICTURE_HEADERS             143
#define IDS_PP1_HEADER_TITLE            144
#define IDS_PP1_HEADER_SUBTITLE         145
#define IDS_PP2_HEADER_TITLE            146
#define IDS_PP2_HEADER_SUBTITLE         147
#define IDC_EDIT_TITLE                  1000
#define IDC_PP0_BUTTON1                 1001
#define IDC_PP1_LISTVIEW                1003
#define IDC_PP3_EDIT3                   1004
#define IDC_PP1_BUTTON_MODIFY           1005
#define IDC_PP2_EDIT_TITLE              1006
#define IDC_PP2_CHECKBOX                1007
#define IDC_PH_STATIC_SUBMODEL          1008
#define IDC_PP2_STATIC                  1009
#define IDC_STATIC3                     1010
#define IDC_CHECK2                      1011
#define IDC_PP3_BUTTON1                 1012
#define IDC_PP3_CHECK1                  1013
#define IDC_PP3_EDIT2                   1014
#define IDC_PP3_STATIC2                 1015
#define IDC_PP3_STATIC                  1016
#define IDC_PP3_CHECK2                  1017
#define IDC_PP3_STATIC3                 1018
#define IDC_PP3_STATIC4                 1019
#define IDC_PP3_STATIC5                 1020
#define IDC_PP2_EDIT3                   1021
#define IDC_PP2_EDIT_NAME               1024
#define IDC_PP3_EDIT1                   1025
#define IDC_RP_EDIT_NAME                1026
#define IDC_WELCOME_RADIO1              1028
#define IDC_WP_RADIO                    1029
#define IDC_WP_RADIO2                   1030
#define IDC_WP_RADIO3                   1031
#define IDC_WP_PROGRESS                 1032
#define IDC_PP0_RADIO1                  1033
#define IDC_PP0_CB_SHOWTOOLTIPS         1034
#define IDC_AP_ACTIVATION_CODE          1035
#define IDC_AP_EMAIL                    1036
#define IDC_WP_STATIC_GROUPBOX          1037
#define IDC_WP_STATIC2                  1038
#define IDC_APP_STATIC                  1039
#define IDC_AP_STATIC4                  1039
#define IDC_WP_STATIC_TITLE             1041
#define IDC_PH_LIST                     1042
#define IDC_PH_BUTTON_MOVEUP            1044
#define IDC_PP0_COMBOBOX                1047
#define IDC_PH_BUTTON_RESIZE            1048
#define IDC_PH_EDIT_XML_MAKE            1049
#define IDC_PH_EDIT_XML_SUBMODEL        1050
#define IDC_PH_EDIT_XML_YEAR            1051
#define IDC_PH_EDIT_XML_TYPE            1052
#define IDC_PH_EDIT_XML_PRICE           1053
#define IDC_PH_EDIT_XML_COUNTRY         1054
#define IDC_PH_EDIT_XML_LENGTH          1055
#define IDC_PH_EDIT_XML_WIDTH           1056
#define IDC_PH_EDIT_XML_HEIGHT          1057
#define IDC_PH_EDIT_XML_WEIGHT          1058
#define IDC_PH_EDIT_XML_CLEARANCE       1059
#define IDC_PH_EDIT_XML_POWER           1060
#define IDC_PH_EDIT_XML_TANK_VOLUME     1061
#define IDC_PH_EDIT_XML_FUEL            1062
#define IDC_PH_BUTTON_SAVE              1063
#define IDC_PP0_STATIC3                 1064
#define IDC_PP1_BUTTON_ADD              1065
#define IDC_PP1_BUTTON_DELETE           1066
#define IDC_PP2_EDIT_LOCATION           1067
#define IDC_PP2_EDIT_SETUP_NAME         1068
#define IDC_PP2_BUTTON_CHANGE           1069
#define IDC_PP2_STATIC5                 1070
#define IDC_PP2_STATIC6                 1071
#define IDC_PP2_STATIC7                 1072
#define IDC_PP2_PROGRESSBAR             1073
#define IDC_PP2_BUTTON_MORE_PARAMS      1074
#define IDC_OS_LISTVIEW                 1075
#define IDC_OS_STATIC_MESSAGE           1076
#define IDC_PP0_STATIC2                 1077
#define IDC_PP0_COMBOBOX2               1078
#define IDC_CP_EDIT                     1079
#define IDC_PP0_EDIT                    1080
#define IDC_EP_EDIT                     1081
#define IDC_PH_BUTTON_CLOSE             1082
#define IDC_PH_BUTTON_SAVECLOSE         1083
#define IDC_PP0_STATIC_GROUPBOX         1084
#define IDC_PP0_RADIO2                  1085
#define IDC_PP0_RADIO3                  1086
#define IDC_PP0_STATIC                  1087
#define IDC_PP2_STATIC_GROUPBOX         1088
#define IDC_PP2_STATIC_GROUPBOX2        1089
#define IDC_PP2_STATIC4                 1090
#define IDC_PP2_STATIC3                 1091
#define IDC_PH_BUTTON_CHANGE_PICTURE    1092
#define IDC_PH_BUTTON_MOVEDOWN          1093
#define IDC_RP_ACTIVATION_CODE          1094
#define IDC_PH_EDIT_XML_MODEL           1095
#define IDC_WP_CHECKBOX                 1096
#define IDC_PP2_STATIC2                 1097
#define IDC_OS_STATIC                   1098
#define IDC_PH_STATIC_GROUPLINE         1099
#define IDC_PH_STATIC_GROUPLINE2        1100
#define IDC_PH_STATIC_GROUPLINE3        1101
#define IDC_PH_STATIC_GROUPLINE4        1102
#define IDC_STATIC_TITLE                1103
#define IDC_PH_STATIC_YEAR              1104
#define IDC_PH_STATIC_MAKE              1105
#define IDC_PH_STATIC_MODEL             1106
#define IDC_PH_STATIC_TYPE              1107
#define IDC_PH_STATIC_PRICE             1108
#define IDC_PH_STATIC_POWER             1109
#define IDC_PH_STATIC_FUEL              1110
#define IDC_PH_STATIC_LENGTH            1111
#define IDC_PH_STATIC_WIDTH             1112
#define IDC_PH_STATIC_HEIGHT            1113
#define IDC_PH_STATIC_CLEARANCE         1114
#define IDC_PH_STATIC_WEIGHT            1115
#define IDC_PH_STATIC_TANK_VOLUME       1116
#define IDC_PH_STATIC_COUNTRY           1117
#define IDC_PH_PREVIEW_WINDOW           1118
#define IDC_WP_STATIC_HEADER            1119
#define IDC_WP_STATIC_HEADER2           1120
#define IDC_WP_STATIC_HEADER3           1121
#define IDC_AP_STATIC                   1122
#define IDC_AP_STATIC2                  1123
#define IDC_AP_STATIC3                  1124
#define IDC_PH_BUTTON_FROMXML           1125
#define IDH_EDIT_TITLE                  2000
#define IDH_PP0_BUTTON1                 2001
#define IDH_PP1_LISTVIEW                2003
#define IDH_PP1_BUTTON_MODIFY           2005
#define IDH_PP2_EDIT_TITLE              2006
#define IDH_PP2_CHECKBOX                2007
#define IDH_PP2_EDIT_NAME               2024
#define IDH_WP_RADIO                    2029
#define IDH_WP_RADIO2                   2030
#define IDH_WP_RADIO3                   2031
#define IDH_WP_PROGRESS                 2032
#define IDH_PP0_RADIO1                  2033
#define IDH_AP_ACTIVATION_CODE          2035
#define IDH_AP_EMAIL                    2036
#define IDH_WP_STATIC_GROUPBOX          2037
#define IDH_WP_STATIC2                  2038
#define IDH_AP_STATIC4                  2039
#define IDH_PH_LIST                     2042
#define IDH_PH_BUTTON_MOVEUP            2044
#define IDH_PP0_COMBOBOX                2047
#define IDH_PH_BUTTON_RESIZE            2048
#define IDH_PH_EDIT_XML_MAKE            2049
#define IDH_PH_EDIT_XML_SUBMODEL        2050
#define IDH_PH_EDIT_XML_YEAR            2051
#define IDH_PH_EDIT_XML_TYPE            2052
#define IDH_PH_EDIT_XML_PRICE           2053
#define IDH_PH_EDIT_XML_COUNTRY         2054
#define IDH_PH_EDIT_XML_LENGTH          2055
#define IDH_PH_EDIT_XML_WIDTH           2056
#define IDH_PH_EDIT_XML_HEIGHT          2057
#define IDH_PH_EDIT_XML_WEIGHT          2058
#define IDH_PH_EDIT_XML_CLEARANCE       2059
#define IDH_PH_EDIT_XML_POWER           2060
#define IDH_PH_EDIT_XML_TANK_VOLUME     2061
#define IDH_PH_EDIT_XML_FUEL            2062
#define IDH_PH_BUTTON_SAVE              2063
#define IDH_PP1_BUTTON_ADD              2065
#define IDH_PP1_BUTTON_DELETE           2066
#define IDH_PP2_EDIT_LOCATION           2067
#define IDH_PP2_EDIT_SETUP_NAME         2068
#define IDH_PP2_BUTTON_CHANGE           2069
#define IDH_PP2_STATIC6                 2071
#define IDH_PP2_PROGRESSBAR             2073
#define IDH_PP2_BUTTON_MORE_PARAMS      2074
#define IDH_OS_LISTVIEW                 2075
#define IDH_OS_STATIC_MESSAGE           2076
#define IDH_PP0_COMBOBOX2               2078
#define IDH_PP0_EDIT                    2080
#define IDH_PH_BUTTON_CLOSE             2082
#define IDH_PH_BUTTON_SAVECLOSE         2083
#define IDH_PP0_STATIC_GROUPBOX         2084
#define IDH_PP0_RADIO2                  2085
#define IDH_PP0_RADIO3                  2086
#define IDH_PP2_STATIC_GROUPBOX         2088
#define IDH_PP2_STATIC_GROUPBOX2        2089
#define IDH_PP2_STATIC4                 2090
#define IDH_PH_BUTTON_CHANGE_PICTURE    2092
#define IDH_PH_BUTTON_MOVEDOWN          2093
#define IDH_PH_EDIT_XML_MODEL           2095
#define IDH_WP_CHECKBOX                 2096
#define IDH_PH_STATIC_GROUPLINE         2099
#define IDH_PP0_BACK                    2100
#define IDH_PH_STATIC_GROUPLINE3        2101
#define IDH_PH_STATIC_GROUPLINE4        2102
#define IDH_PP0_NEXT                    2103
#define IDH_PP0_CANCEL                  2105
#define IDH_PP0_HELP                    2106
#define IDH_PP0_FINISH                  2107
#define IDH_PH_PREVIEW_WINDOW           2118
#define IDH_PH_STATIC_GROUPLINE2        2119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
